- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Filebeat service
  ansible.builtin.service:
    name: filebeat
    enabled: true
    state: restarted
  register: myservice
  until: ('status' in myservice) and (myservice.status.ActiveState == "active")
  retries: 5
  delay: 60

- name: Update update-ca-trust
  ansible.builtin.command: update-ca-trust
  register: updated_ca_trust
  changed_when: updated_ca_trust.rc == 0
